# Keep this configuration synced with Turtles.
# See: https://raw.githubusercontent.com/rancher/turtles/refs/tags/v0.24.0-rc.0/test/e2e/config/operator.yaml

managementClusterName: rancher-turtles-integration

intervals:
  default/wait-controllers: ["15m", "10s"]
  default/wait-rancher: ["15m", "30s"]
  default/wait-delete-cluster: ["30m", "30s"]
  default/wait-gitpush: ["3m", "10s"]
  default/wait-consistently: ["30s", "5s"]
  default/wait-turtles-uninstall: ["10m", "30s"]
  default/wait-capiprovider-update: ["5m", "10s"]

variables:
  # General Configuration
  NAMESPACE: "default"
  MANAGEMENT_CLUSTER_ENVIRONMENT: "isolated-kind" # supported options: eks, isolated-kind, kind
  USE_EXISTING_CLUSTER: "false"
  SKIP_RESOURCE_CLEANUP: "false"
  SKIP_DELETION_TEST: "false"
  ARTIFACTS_FOLDER: "_artifacts"
  SECRET_KEYS: "NGROK_AUTHTOKEN,NGROK_API_KEY,RANCHER_HOSTNAME,RANCHER_PASSWORD,CAPG_ENCODED_CREDS,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AZURE_SUBSCRIPTION_ID,AZURE_CLIENT_ID,AZURE_CLIENT_SECRET,AZURE_TENANT_ID,GCP_PROJECT,GCP_NETWORK_NAME,GCP_IMAGE_ID,VSPHERE_TLS_THUMBPRINT,VSPHERE_SERVER,VSPHERE_DATACENTER,VSPHERE_DATASTORE,VSPHERE_FOLDER,VSPHERE_TEMPLATE,VSPHERE_NETWORK,VSPHERE_RESOURCE_POOL,VSPHERE_USERNAME,VSPHERE_PASSWORD,VSPHERE_KUBE_VIP_IP_KUBEADM,VSPHERE_KUBE_VIP_IP_RKE2,DOCKER_REGISTRY_TOKEN,DOCKER_REGISTRY_USERNAME,DOCKER_REGISTRY_CONFIG"

  # Kubernetes Configuration
  KUBERNETES_VERSION: "v1.31.4"
  KUBERNETES_MANAGEMENT_VERSION: "v1.31.4"
  RKE2_VERSION: "v1.31.7+rke2r1"

  # CLI Tool Paths
  HELM_EXTRA_VALUES_FOLDER: "/tmp"

  # Rancher Configuration
  RANCHER_VERSION: "v2.12.1"
  RANCHER_REPO_NAME: "rancher-latest"
  RANCHER_PATH: "rancher-latest/rancher"
  RANCHER_URL: "https://releases.rancher.com/server-charts/latest"
  RANCHER_FEATURES: ""
  RANCHER_HOSTNAME: "localhost"
  RANCHER_PASSWORD: "rancheradmin"

  # Turtles Configuration
  TURTLES_VERSION: "v0.24.0-rc.0"
  TURTLES_REPO_NAME: "rancher-turtles"
  TURTLES_URL: "https://rancher.github.io/turtles"

  # External Charts and Dependencies
  CERT_MANAGER_REPO_NAME: "jetstack"
  CERT_MANAGER_URL: "https://charts.jetstack.io"
  CERT_MANAGER_PATH: "jetstack/cert-manager"
  CPI_IMAGE_K8S_VERSION: "v1.31.0"

  # Ingress Configuration (Ngrok)
  NGROK_REPO_NAME: "ngrok"
  NGROK_URL: "https://charts.ngrok.com"
  NGROK_PATH: "ngrok/ngrok-operator"
  NGROK_API_KEY: ""
  NGROK_AUTHTOKEN: ""
